# dev, not production
development: True
production: False
deployment_environment: dev

crypton_source_repository: https://github.com/SpiderOak/crypton.git
crypton_checkout: "/home/{{ ansible_user_id }}/crypton"

crypton_server_domain: cryptondev.local
crypton_server_local_port: 40087

database_master: "{{ inventory_hostname }}"
# no db slaves present
database_slaves: []


# mapping of groups of machines, which database users and databases they
# are allowed to connect to.
pg_hba_group_access:
  - { group: "crypton_server", user: "crypton_server", db: "crypton_server" }
