---

timestamp: "{{ lookup('pipe', 'date +%s') }}"

db:
 username: crypton_server
 password: |
   {{ lookup('password',
        inventory_dir
        + '/secrets/'
        + deployment_environment
        + '/auto/crypton_server.passwd
      chars=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789') }}
 name: crypton_server
 host: "{{ database_master|default('localhost') }}"
 port: 5432
